title: Abdul-Mugis Personal Website
email: mugis.yussif@connect.polyu.hk
description: >- # this means to ignore newlines until "baseurl:"
  A minimal Jekyll theme to host your resume.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jerwuney.github.io/" # the base hostname & protocol for your site
linkedin_username: "linkedin.com/in/amyussif/"
github_username:  Jerwuney

# Build settings
theme: minima
