title: Abdul-Mugis's Personal Website
email: mugis.yussif@connect.polyu.hk
description: >- # this means to ignore newlines until "baseurl:"
  Feel free to connect if our interest align.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jerwuney.github.io/" # the base hostname & protocol for your site
linkedin_username: "https://www.linkedin.com/in/amyussif/"
github_username:  Jerwuney

# Build settings
theme: minima
